[package]
name = "tokio-serial"
version = "4.4.0-beta1"
authors = ["Zac Berkowitz <zac.berkowitz@gmail.com>"]
description = "A serial port implementation for tokio"
license = "MIT"
homepage = "https://github.com/berkowski/tokio-serial"
repository = "https://github.com/berkowski/tokio-serial"
documentation = "http://docs.rs/tokio-serial"
readme = "README.md"
keywords = ["rs232", "serial", "tokio"]
categories = ["asynchronous", "hardware-support"]
edition = "2018"

[badges]
appveyor = { repository = "berkowski/tokio-serial", service = "github" }
travis-ci = { repository = "berkowski/tokio-serial", service = "github" }

[features]
default = ["libudev"]
libudev = ["mio-serial/libudev"]
rt = ["tokio/rt-multi-thread"]

[dependencies]
futures = "0.3"
tokio = { version = "1.7.1", default-features = false , features = ["net"]}
mio-serial = { git = "https://github.com/berkowski/mio-serial", branch="v4.0", default-features = false }

[dev-dependencies]
tokio = { version = "1.7.1", features = ["macros"], default-features = false }
tokio-util = { version = "0.6", features = ["codec"], default-features = false }
bytes = "1"

[[example]]
name = "serial_println"
path = "examples/serial_println.rs"
required-features = ["rt"]
